bootstrap:
  storeUnsealKeys: false

networkPolicy:
  enabled: true

recovery:
  triggerId: ""
  selfName: "vault-a"
  fallback:
    addr: "https://vault.kube-vault-b.example.com:8200"
    k8sAuthPath: "auth/kubernetes"
    vaultRole: "vault-recovery-unseal"
    secretPath: ""
    tlsSkipVerify: false
    cidr: "10.0.0.0/8"
  rekey:
    enabled: false
    confirm: false
    syncFallback: false
    experimental: true
    keyShares: 5
    keyThreshold: 3
  encryption:
    enabled: true
    passphraseSecret: "vault-recovery-passphrase"

vault:
  server:
    ha:
      enabled: true
      raft:
        enabled: true
