bootstrap:
  storeUnsealKeys: true
  keyShares: 1
  keyThreshold: 1

networkPolicy:
  enabled: false

recovery:
  triggerId: ""
  rekey:
    enabled: false
    confirm: false
    syncFallback: false
    experimental: true
    keyShares: 1
    keyThreshold: 1
  encryption:
    enabled: false

vault:
  server:
    affinity: ""
    ha:
      enabled: true
      raft:
        enabled: true
