bootstrap:
  holdInitMaterialSeconds: 0
  store:
    k8sSecret:
      enabled: false

networkPolicy:
  enabled: true

recovery:
  manualJob:
    triggerId: ""
  selfName: "vault-a"
  fallback:
    addr: "https://vault.kube-vault-b.example.com:8200"
    k8sAuthPath: "auth/kubernetes-vault-a"
    vaultRole: "vault-recovery-unseal"
    rekeyVaultRole: "vault-recovery-rekey-sync"
    secretPath: ""
    tlsSkipVerify: false
    cidr: "10.0.0.0/8"
  rekey:
    enabled: false
    confirm: false
    syncFallback: false
    experimental: true
    keyShares: 5
    keyThreshold: 3
  encryption:
    enabled: true
    passphraseSecret: "vault-recovery-passphrase"

vault:
  server:
    ha:
      enabled: true
    volumes:
      - name: recovery-prep
        emptyDir:
          medium: Memory
      - name: recovery-init-script
        configMap:
          name: vault-recovery-init-script
          defaultMode: 0755
      - name: vault-poststart-script
        configMap:
          name: vault-poststart-script
          defaultMode: 0755
      - name: vault-recovery-passphrase
        secret:
          secretName: vault-recovery-passphrase
          items:
            - key: passphrase
              path: passphrase
      - name: vault-recovery-token
        secret:
          secretName: vault-recovery-token
    volumeMounts:
      - name: recovery-prep
        mountPath: /vault/recovery-prep
      - name: vault-poststart-script
        mountPath: /vault/scripts/poststart
        readOnly: true
      - name: vault-recovery-passphrase
        mountPath: /vault/recovery-passphrase
        readOnly: true
