{{- if and .Values.recovery.manualJob.triggerId .Values.networkPolicy.enabled (not .Values.recovery.fallback.cidr) }}
{{- fail "Set recovery.fallback.cidr to restrict NetworkPolicy egress when triggering recovery with networkPolicy.enabled=true" }}
{{- end }}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-init-job
spec:
  podSelector:
    matchLabels:
      app: vault-wait
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: vault
    ports:
    - port: 8200
      protocol: TCP
  - ports:
    - port: 443
      protocol: TCP
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-server
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: vault
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: vault-wait
    - podSelector:
        matchLabels:
          app: vault-recovery
    - podSelector:
        matchLabels:
          app: vault-rekey
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: vault
    ports:
    - port: 8200
      protocol: TCP
    - port: 8201
      protocol: TCP
  {{- if .Values.networkPolicy.allowClientPodLabels }}
  - from:
    - podSelector:
        matchLabels: {{ .Values.networkPolicy.allowClientPodLabels | toJson }}
    ports:
    - port: 8200
      protocol: TCP
  {{- end }}
  {{- range .Values.networkPolicy.allowClientNamespaces }}
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ . }}
    ports:
    - port: 8200
      protocol: TCP
  {{- end }}
{{- if .Values.recovery.manualJob.triggerId }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vault-recovery-job
spec:
  podSelector:
    matchLabels:
      app: vault-recovery
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: vault
    ports:
    - port: 8200
      protocol: TCP
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  {{- if .Values.recovery.fallback.cidr }}
  - to:
    - ipBlock:
        cidr: {{ .Values.recovery.fallback.cidr }}
    ports:
    - port: 8200
      protocol: TCP
    - port: 443
      protocol: TCP
  {{- end }}
{{- end }}
{{- end }}
