{{- if .Values.recovery.manualJob.triggerId }}
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-recovery-{{ .Values.recovery.manualJob.triggerId | lower | replace "_" "-" | replace "." "-" | trunc 47 | trimSuffix "-" }}
  annotations:
    "helm.sh/hook": post-upgrade,post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  ttlSecondsAfterFinished: 300
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: vault-recovery
    spec:
      serviceAccountName: vault-recovery
      initContainers:
      - name: recovery-auth
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [sh, /vault/scripts/recovery-init/recovery-init.sh]
        env:
          - name: SKIP_ACTIVE_CHECK
            value: "true"
        volumeMounts:
          - name: recovery-data
            mountPath: /vault/recovery-prep
          - name: recovery-init-script
            mountPath: /vault/scripts/recovery-init
      containers:
      - name: recovery-unseal
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [sh, /vault/scripts/poststart/poststart.sh]
        env:
          - name: PREP_DIR
            value: /vault/recovery-prep
          - name: UNSEAL_TARGETS
            value: "{{ join " " .Values.recovery.manualJob.targets }}"
          - name: SKIP_RAFT_JOIN
            value: "true"
        volumeMounts:
        - name: recovery-data
          mountPath: /vault/recovery-prep
        - name: poststart-script
          mountPath: /vault/scripts/poststart
        {{- if .Values.recovery.encryption.enabled }}
        - name: encryption-passphrase
          mountPath: /vault/recovery-passphrase
          readOnly: true
        {{- end }}
      restartPolicy: OnFailure
      volumes:
      - name: recovery-data
        emptyDir:
          medium: Memory
      - name: recovery-init-script
        configMap:
          name: vault-recovery-init-script
          defaultMode: 0755
      - name: poststart-script
        configMap:
          name: vault-poststart-script
          defaultMode: 0755
      {{- if .Values.recovery.encryption.enabled }}
      - name: encryption-passphrase
        secret:
          secretName: {{ .Values.recovery.encryption.passphraseSecret }}
          items:
          - key: passphrase
            path: passphrase
      {{- end }}
  backoffLimit: 3
{{- end }}
