---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-recovery
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-recovery-token
  annotations:
    kubernetes.io/service-account.name: vault-recovery
type: kubernetes.io/service-account-token
