---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-reviewer
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-reviewer-token
  annotations:
    kubernetes.io/service-account.name: vault-reviewer
type: kubernetes.io/service-account-token
